import type { FoodShop } from './types';

// 模拟数据 - 基于真实场景构造的上榜美食店铺
// 以杭州西湖周边为例
export function generateMockShops(lat: number, lng: number): FoodShop[] {
  const shops: FoodShop[] = [
    {
      id: 'dp-001',
      name: '知味观·总店',
      category: '浙菜',
      rating: 4.8,
      reviewCount: 12580,
      avgPrice: 128,
      address: '上城区仁和路83号',
      distance: 0,
      latitude: lat + 0.003,
      longitude: lng + 0.002,
      image: '',
      tags: ['老字号', '必吃榜', '家庭聚餐'],
      source: 'both',
      isOnList: true,
      listName: '大众点评必吃榜',
      openTime: '10:30-21:00',
    },
    {
      id: 'dp-002',
      name: '外婆家·西湖店',
      category: '浙菜',
      rating: 4.6,
      reviewCount: 28930,
      avgPrice: 72,
      address: '上城区湖滨路3号',
      distance: 0,
      latitude: lat + 0.005,
      longitude: lng - 0.003,
      image: '',
      tags: ['排队王', '高性价比', '约会推荐'],
      source: 'dianping',
      isOnList: true,
      listName: '大众点评必吃榜',
      openTime: '10:00-21:30',
    },
    {
      id: 'gd-001',
      name: '奎元馆·解放路店',
      category: '面食',
      rating: 4.5,
      reviewCount: 8760,
      avgPrice: 45,
      address: '上城区解放路152号',
      distance: 0,
      latitude: lat + 0.002,
      longitude: lng + 0.005,
      image: '',
      tags: ['百年老店', '片儿川', '扫街榜TOP10'],
      source: 'gaode',
      isOnList: true,
      listName: '高德扫街榜',
      openTime: '06:30-20:30',
    },
    {
      id: 'dp-003',
      name: '新白鹿·湖滨银泰店',
      category: '浙菜',
      rating: 4.7,
      reviewCount: 15620,
      avgPrice: 85,
      address: '上城区东坡路1号湖滨银泰',
      distance: 0,
      latitude: lat + 0.004,
      longitude: lng - 0.001,
      image: '',
      tags: ['必吃榜', '排队名店', '糖醋排条'],
      source: 'both',
      isOnList: true,
      listName: '大众点评必吃榜',
      openTime: '10:30-21:00',
    },
    {
      id: 'gd-002',
      name: '葱包桧·河坊街店',
      category: '小吃快餐',
      rating: 4.3,
      reviewCount: 3420,
      avgPrice: 18,
      address: '上城区河坊街218号',
      distance: 0,
      latitude: lat + 0.001,
      longitude: lng + 0.004,
      image: '',
      tags: ['街头小吃', '扫街榜', '地道风味'],
      source: 'gaode',
      isOnList: true,
      listName: '高德扫街榜',
      openTime: '08:00-22:00',
    },
    {
      id: 'dp-004',
      name: '弄堂里·中山中路店',
      category: '浙菜',
      rating: 4.6,
      reviewCount: 6890,
      avgPrice: 95,
      address: '上城区中山中路316号',
      distance: 0,
      latitude: lat - 0.002,
      longitude: lng + 0.003,
      image: '',
      tags: ['必吃榜', '老杭州味道', '环境优雅'],
      source: 'dianping',
      isOnList: true,
      listName: '大众点评必吃榜',
      openTime: '11:00-14:00 17:00-21:00',
    },
    {
      id: 'gd-003',
      name: '阿娘面馆·武林路店',
      category: '面食',
      rating: 4.4,
      reviewCount: 5230,
      avgPrice: 38,
      address: '下城区武林路268号',
      distance: 0,
      latitude: lat + 0.008,
      longitude: lng + 0.002,
      image: '',
      tags: ['扫街榜', '黄鱼面', '深夜食堂'],
      source: 'gaode',
      isOnList: true,
      listName: '高德扫街榜',
      openTime: '10:00-02:00',
    },
    {
      id: 'dp-005',
      name: '绿茶餐厅·龙井船宴',
      category: '浙菜',
      rating: 4.5,
      reviewCount: 19870,
      avgPrice: 68,
      address: '西湖区龙井路8号',
      distance: 0,
      latitude: lat - 0.005,
      longitude: lng - 0.004,
      image: '',
      tags: ['必吃榜', '船宴体验', '茶园景观'],
      source: 'both',
      isOnList: true,
      listName: '大众点评必吃榜',
      openTime: '10:30-21:00',
    },
    {
      id: 'gd-004',
      name: '老鸭集·煲',
      category: '火锅/煲',
      rating: 4.6,
      reviewCount: 7650,
      avgPrice: 110,
      address: '拱墅区湖墅南路108号',
      distance: 0,
      latitude: lat + 0.01,
      longitude: lng - 0.002,
      image: '',
      tags: ['扫街榜TOP5', '老鸭煲', '冬季必吃'],
      source: 'gaode',
      isOnList: true,
      listName: '高德扫街榜',
      openTime: '11:00-22:00',
    },
    {
      id: 'dp-006',
      name: '老头儿油爆虾·总店',
      category: '浙菜',
      rating: 4.4,
      reviewCount: 9340,
      avgPrice: 88,
      address: '上城区中山中路206号',
      distance: 0,
      latitude: lat - 0.001,
      longitude: lng + 0.006,
      image: '',
      tags: ['必吃榜', '油爆虾', '30年老店'],
      source: 'both',
      isOnList: true,
      listName: '大众点评必吃榜',
      openTime: '10:30-14:00 16:30-21:00',
    },
    {
      id: 'gd-005',
      name: '煎饼果子·武林夜市',
      category: '小吃快餐',
      rating: 4.2,
      reviewCount: 2180,
      avgPrice: 12,
      address: '下城区武林夜市B18摊位',
      distance: 0,
      latitude: lat + 0.009,
      longitude: lng + 0.004,
      image: '',
      tags: ['扫街榜', '夜市人气王', '现做现卖'],
      source: 'gaode',
      isOnList: true,
      listName: '高德扫街榜',
      openTime: '17:00-23:00',
    },
    {
      id: 'dp-007',
      name: '楼外楼·孤山路店',
      category: '浙菜',
      rating: 4.3,
      reviewCount: 22100,
      avgPrice: 168,
      address: '西湖区孤山路30号',
      distance: 0,
      latitude: lat + 0.006,
      longitude: lng - 0.008,
      image: '',
      tags: ['百年老字号', '西湖醋鱼', '游客必去'],
      source: 'dianping',
      isOnList: true,
      listName: '大众点评必吃榜',
      openTime: '11:00-14:00 17:00-20:30',
    },
    {
      id: 'gd-006',
      name: '慧娟面馆',
      category: '面食',
      rating: 4.5,
      reviewCount: 4560,
      avgPrice: 32,
      address: '上城区望江路128号',
      distance: 0,
      latitude: lat - 0.006,
      longitude: lng + 0.005,
      image: '',
      tags: ['扫街榜', '笋干面', '社区口碑店'],
      source: 'gaode',
      isOnList: true,
      listName: '高德扫街榜',
      openTime: '06:00-14:00',
    },
    {
      id: 'dp-008',
      name: '甘其食·包子铺',
      category: '小吃快餐',
      rating: 4.1,
      reviewCount: 6780,
      avgPrice: 15,
      address: '上城区延安路292号',
      distance: 0,
      latitude: lat + 0.003,
      longitude: lng - 0.005,
      image: '',
      tags: ['必吃榜', '鲜肉包', '早餐首选'],
      source: 'dianping',
      isOnList: true,
      listName: '大众点评必吃榜',
      openTime: '06:00-20:00',
    },
    {
      id: 'gd-007',
      name: '方老大面·城站店',
      category: '面食',
      rating: 4.7,
      reviewCount: 8920,
      avgPrice: 42,
      address: '上城区城站路56号',
      distance: 0,
      latitude: lat - 0.004,
      longitude: lng + 0.008,
      image: '',
      tags: ['扫街榜TOP3', '大排面', '本地人推荐'],
      source: 'both',
      isOnList: true,
      listName: '双榜上榜',
      openTime: '06:30-14:00 17:00-20:30',
    },
  ];

  // 计算距离
  return shops.map((shop) => ({
    ...shop,
    distance: getDistance(lat, lng, shop.latitude, shop.longitude),
  }));
}

// Haversine公式计算两点距离（单位：km）
function getDistance(
  lat1: number,
  lng1: number,
  lat2: number,
  lng2: number
): number {
  const R = 6371;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLng = ((lng2 - lng1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLng / 2) *
      Math.sin(dLng / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Math.round(R * c * 1000) / 1000;
}
